CREATE TABLE INDEXES_BY_COL (
  DB_ID INT NOT ,
  TID INT NOT ,
  COLUMN_NAME VARCHAR(128) NOT NULL,
  INDEX_ID INT NOT NULL ,
  PRIMARY KEY (DB_ID, TID, COLUMN_NAME),
  FOREIGN KEY (DB_ID) REFERENCES DATABASES_ (DB_ID) ON DELETE CASCADE,
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE,
  FOREIGN KEY (INDEX_ID) REFERENCES INDEXES (INDEX_ID) ON DELETE CASCADE,
)