CREATE TABLE PARTITIONS (
  PID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TID INT NOT NULL,
  PARTITION_NAME VARCHAR(767) BINARY,
  PATH VARCHAR(4096),
  UNIQUE INDEX PARTITIONS_IDX (PID, TID, PARTITION_NAME),
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE)