CREATE TABLE TABLES (
  TID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DB_ID INT NOT NULL,
  TABLE_NAME VARCHAR(128) NOT NULL,
  TABLE_TYPE VARCHAR(128) NOT NULL,
  PATH VARCHAR(4096),
  STORE_TYPE CHAR(16),
  FOREIGN KEY (DB_ID) REFERENCES DATABASES_ (DB_ID),
  INDEX IDX_DB_ID (DB_ID),
  UNIQUE INDEX IDX_TABLE_ID (DB_ID, TABLE_NAME)
)