CREATE TABLE TABLESPACES (
  SPACE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SPACE_NAME VARCHAR(128) NOT NULL UNIQUE,
  SPACE_HANDLER VARCHAR (1024) DEFAULT 'HDFS',
  SPACE_URI VARCHAR (4096) NOT NULL,
  UNIQUE INDEX IDX_NAME (SPACE_NAME)
)