CREATE TABLE PARTSUPP (
  PS_PARTKEY     INTEGER NOT NULL,
  PS_SUPPKEY     INTEGER NOT NULL,
  PS_AVAILQTY    INTEGER NOT NULL,
  PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
  PS_COMMENT     VARCHAR(199) NOT NULL
);