CREATE TABLE PARTITIONS (
  PID INT NOT NULL PRIMARY KEY,
  TID INT NOT NULL,
  PARTITION_NAME VARCHAR2(128),
  ORDINAL_POSITION INT NOT NULL,
  PARTITION_VALUE VARCHAR2(1024),
  PATH VARCHAR2(4000),
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE,
  CONSTRAINT C_PARTITION_UNIQUE UNIQUE (TID, PARTITION_NAME)
)