CREATE TABLE PARTITION_METHODS (
  TID INT NOT NULL PRIMARY KEY,
  PARTITION_TYPE VARCHAR2(10) NOT NULL,
  EXPRESSION VARCHAR2(1024) NOT NULL,
  EXPRESSION_SCHEMA RAW(1024) NOT NULL,
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
)
