CREATE TABLE OPTIONS (
  TID INT NOT NULL,
  KEY_ VARCHAR2(255) NOT NULL,
  VALUE_ VARCHAR2(255) NOT NULL,
  CONSTRAINT OPTIONS_PKEY PRIMARY KEY (TID, KEY_),
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
)