// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IndexProtos.proto

package tajo.storage.index;

public final class IndexProtos {
  private IndexProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TupleComparatorProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .SortSpecProto sortSpecs = 1;
    java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto> 
        getSortSpecsList();
    tajo.catalog.proto.CatalogProtos.SortSpecProto getSortSpecs(int index);
    int getSortSpecsCount();
    java.util.List<? extends tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder> 
        getSortSpecsOrBuilderList();
    tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder getSortSpecsOrBuilder(
        int index);
  }
  public static final class TupleComparatorProto extends
      com.google.protobuf.GeneratedMessage
      implements TupleComparatorProtoOrBuilder {
    // Use TupleComparatorProto.newBuilder() to construct.
    private TupleComparatorProto(Builder builder) {
      super(builder);
    }
    private TupleComparatorProto(boolean noInit) {}
    
    private static final TupleComparatorProto defaultInstance;
    public static TupleComparatorProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public TupleComparatorProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tajo.storage.index.IndexProtos.internal_static_TupleComparatorProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tajo.storage.index.IndexProtos.internal_static_TupleComparatorProto_fieldAccessorTable;
    }
    
    // repeated .SortSpecProto sortSpecs = 1;
    public static final int SORTSPECS_FIELD_NUMBER = 1;
    private java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto> sortSpecs_;
    public java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto> getSortSpecsList() {
      return sortSpecs_;
    }
    public java.util.List<? extends tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder> 
        getSortSpecsOrBuilderList() {
      return sortSpecs_;
    }
    public int getSortSpecsCount() {
      return sortSpecs_.size();
    }
    public tajo.catalog.proto.CatalogProtos.SortSpecProto getSortSpecs(int index) {
      return sortSpecs_.get(index);
    }
    public tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder getSortSpecsOrBuilder(
        int index) {
      return sortSpecs_.get(index);
    }
    
    private void initFields() {
      sortSpecs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getSortSpecsCount(); i++) {
        if (!getSortSpecs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sortSpecs_.size(); i++) {
        output.writeMessage(1, sortSpecs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < sortSpecs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sortSpecs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tajo.storage.index.IndexProtos.TupleComparatorProto)) {
        return super.equals(obj);
      }
      tajo.storage.index.IndexProtos.TupleComparatorProto other = (tajo.storage.index.IndexProtos.TupleComparatorProto) obj;
      
      boolean result = true;
      result = result && getSortSpecsList()
          .equals(other.getSortSpecsList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getSortSpecsCount() > 0) {
        hash = (37 * hash) + SORTSPECS_FIELD_NUMBER;
        hash = (53 * hash) + getSortSpecsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tajo.storage.index.IndexProtos.TupleComparatorProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tajo.storage.index.IndexProtos.TupleComparatorProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements tajo.storage.index.IndexProtos.TupleComparatorProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tajo.storage.index.IndexProtos.internal_static_TupleComparatorProto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tajo.storage.index.IndexProtos.internal_static_TupleComparatorProto_fieldAccessorTable;
      }
      
      // Construct using tajo.index.IndexProtos.TupleComparatorProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSortSpecsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (sortSpecsBuilder_ == null) {
          sortSpecs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sortSpecsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tajo.storage.index.IndexProtos.TupleComparatorProto.getDescriptor();
      }
      
      public tajo.storage.index.IndexProtos.TupleComparatorProto getDefaultInstanceForType() {
        return tajo.storage.index.IndexProtos.TupleComparatorProto.getDefaultInstance();
      }
      
      public tajo.storage.index.IndexProtos.TupleComparatorProto build() {
        tajo.storage.index.IndexProtos.TupleComparatorProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tajo.storage.index.IndexProtos.TupleComparatorProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        tajo.storage.index.IndexProtos.TupleComparatorProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tajo.storage.index.IndexProtos.TupleComparatorProto buildPartial() {
        tajo.storage.index.IndexProtos.TupleComparatorProto result = new tajo.storage.index.IndexProtos.TupleComparatorProto(this);
        int from_bitField0_ = bitField0_;
        if (sortSpecsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sortSpecs_ = java.util.Collections.unmodifiableList(sortSpecs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sortSpecs_ = sortSpecs_;
        } else {
          result.sortSpecs_ = sortSpecsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tajo.storage.index.IndexProtos.TupleComparatorProto) {
          return mergeFrom((tajo.storage.index.IndexProtos.TupleComparatorProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tajo.storage.index.IndexProtos.TupleComparatorProto other) {
        if (other == tajo.storage.index.IndexProtos.TupleComparatorProto.getDefaultInstance()) return this;
        if (sortSpecsBuilder_ == null) {
          if (!other.sortSpecs_.isEmpty()) {
            if (sortSpecs_.isEmpty()) {
              sortSpecs_ = other.sortSpecs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSortSpecsIsMutable();
              sortSpecs_.addAll(other.sortSpecs_);
            }
            onChanged();
          }
        } else {
          if (!other.sortSpecs_.isEmpty()) {
            if (sortSpecsBuilder_.isEmpty()) {
              sortSpecsBuilder_.dispose();
              sortSpecsBuilder_ = null;
              sortSpecs_ = other.sortSpecs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sortSpecsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSortSpecsFieldBuilder() : null;
            } else {
              sortSpecsBuilder_.addAllMessages(other.sortSpecs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getSortSpecsCount(); i++) {
          if (!getSortSpecs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder subBuilder = tajo.catalog.proto.CatalogProtos.SortSpecProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSortSpecs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .SortSpecProto sortSpecs = 1;
      private java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto> sortSpecs_ =
        java.util.Collections.emptyList();
      private void ensureSortSpecsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sortSpecs_ = new java.util.ArrayList<tajo.catalog.proto.CatalogProtos.SortSpecProto>(sortSpecs_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          tajo.catalog.proto.CatalogProtos.SortSpecProto, tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder, tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder> sortSpecsBuilder_;
      
      public java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto> getSortSpecsList() {
        if (sortSpecsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sortSpecs_);
        } else {
          return sortSpecsBuilder_.getMessageList();
        }
      }
      public int getSortSpecsCount() {
        if (sortSpecsBuilder_ == null) {
          return sortSpecs_.size();
        } else {
          return sortSpecsBuilder_.getCount();
        }
      }
      public tajo.catalog.proto.CatalogProtos.SortSpecProto getSortSpecs(int index) {
        if (sortSpecsBuilder_ == null) {
          return sortSpecs_.get(index);
        } else {
          return sortSpecsBuilder_.getMessage(index);
        }
      }
      public Builder setSortSpecs(
          int index, tajo.catalog.proto.CatalogProtos.SortSpecProto value) {
        if (sortSpecsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSortSpecsIsMutable();
          sortSpecs_.set(index, value);
          onChanged();
        } else {
          sortSpecsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSortSpecs(
          int index, tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder builderForValue) {
        if (sortSpecsBuilder_ == null) {
          ensureSortSpecsIsMutable();
          sortSpecs_.set(index, builderForValue.build());
          onChanged();
        } else {
          sortSpecsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSortSpecs(tajo.catalog.proto.CatalogProtos.SortSpecProto value) {
        if (sortSpecsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSortSpecsIsMutable();
          sortSpecs_.add(value);
          onChanged();
        } else {
          sortSpecsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSortSpecs(
          int index, tajo.catalog.proto.CatalogProtos.SortSpecProto value) {
        if (sortSpecsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSortSpecsIsMutable();
          sortSpecs_.add(index, value);
          onChanged();
        } else {
          sortSpecsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSortSpecs(
          tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder builderForValue) {
        if (sortSpecsBuilder_ == null) {
          ensureSortSpecsIsMutable();
          sortSpecs_.add(builderForValue.build());
          onChanged();
        } else {
          sortSpecsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSortSpecs(
          int index, tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder builderForValue) {
        if (sortSpecsBuilder_ == null) {
          ensureSortSpecsIsMutable();
          sortSpecs_.add(index, builderForValue.build());
          onChanged();
        } else {
          sortSpecsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSortSpecs(
          java.lang.Iterable<? extends tajo.catalog.proto.CatalogProtos.SortSpecProto> values) {
        if (sortSpecsBuilder_ == null) {
          ensureSortSpecsIsMutable();
          super.addAll(values, sortSpecs_);
          onChanged();
        } else {
          sortSpecsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSortSpecs() {
        if (sortSpecsBuilder_ == null) {
          sortSpecs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sortSpecsBuilder_.clear();
        }
        return this;
      }
      public Builder removeSortSpecs(int index) {
        if (sortSpecsBuilder_ == null) {
          ensureSortSpecsIsMutable();
          sortSpecs_.remove(index);
          onChanged();
        } else {
          sortSpecsBuilder_.remove(index);
        }
        return this;
      }
      public tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder getSortSpecsBuilder(
          int index) {
        return getSortSpecsFieldBuilder().getBuilder(index);
      }
      public tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder getSortSpecsOrBuilder(
          int index) {
        if (sortSpecsBuilder_ == null) {
          return sortSpecs_.get(index);  } else {
          return sortSpecsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder> 
           getSortSpecsOrBuilderList() {
        if (sortSpecsBuilder_ != null) {
          return sortSpecsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sortSpecs_);
        }
      }
      public tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder addSortSpecsBuilder() {
        return getSortSpecsFieldBuilder().addBuilder(
            tajo.catalog.proto.CatalogProtos.SortSpecProto.getDefaultInstance());
      }
      public tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder addSortSpecsBuilder(
          int index) {
        return getSortSpecsFieldBuilder().addBuilder(
            index, tajo.catalog.proto.CatalogProtos.SortSpecProto.getDefaultInstance());
      }
      public java.util.List<tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder> 
           getSortSpecsBuilderList() {
        return getSortSpecsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tajo.catalog.proto.CatalogProtos.SortSpecProto, tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder, tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder> 
          getSortSpecsFieldBuilder() {
        if (sortSpecsBuilder_ == null) {
          sortSpecsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tajo.catalog.proto.CatalogProtos.SortSpecProto, tajo.catalog.proto.CatalogProtos.SortSpecProto.Builder, tajo.catalog.proto.CatalogProtos.SortSpecProtoOrBuilder>(
                  sortSpecs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sortSpecs_ = null;
        }
        return sortSpecsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:TupleComparatorProto)
    }
    
    static {
      defaultInstance = new TupleComparatorProto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TupleComparatorProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TupleComparatorProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TupleComparatorProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021IndexProtos.proto\032\023CatalogProtos.proto" +
      "\"9\n\024TupleComparatorProto\022!\n\tsortSpecs\030\001 " +
      "\003(\0132\016.SortSpecProtoB!\n\ntajo.indexB\013Index" +
      "ProtosH\001\210\001\000\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TupleComparatorProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TupleComparatorProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TupleComparatorProto_descriptor,
              new java.lang.String[] { "SortSpecs", },
              tajo.storage.index.IndexProtos.TupleComparatorProto.class,
              tajo.storage.index.IndexProtos.TupleComparatorProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tajo.catalog.proto.CatalogProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
