CREATE TABLE COLUMNS (
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  COLUMN_NAME VARCHAR(128) NOT NULL,
  ORDINAL_POSITION INTEGER NOT NULL,
  DATA_TYPE CHAR(16),
  TYPE_LENGTH INTEGER,
  CONSTRAINT COLUMNS_PK PRIMARY KEY (TID, COLUMN_NAME)
)