CREATE TABLE INDEXES_BY_COL (
  DB_ID INT NOT NULL REFERENCES DATABASES_ (DB_ID) ON DELETE CASCADE,
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  COLUMN_NAME VARCHAR(128) NOT NULL,
  INDEX_ID INT NOT NULL REFERENCES INDEXES (INDEX_ID) ON DELETE CASCADE,
  CONSTRAINT C_INDEXES_BY_COL_PK PRIMARY KEY (DB_ID, TID, COLUMN_NAME)
)