CREATE TABLE INDEXES (
  DB_ID INT NOT NULL REFERENCES DATABASES_ (DB_ID) ON DELETE CASCADE,
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  INDEX_NAME VARCHAR(128) NOT NULL,
  INDEX_TYPE CHAR(32) NOT NULL,
  PATH VARCHAR(4096),
  COLUMN_NAMES VARCHAR(128) NOT NULL, -- array of column names
  DATA_TYPES VARCHAR(128) NOT NULL, -- array of column types
  ORDERS VARCHAR(128) NOT NULL, -- array of column orders
  NULL_ORDERS VARCHAR(128) NOT NULL, -- array of null orderings
  IS_UNIQUE BOOLEAN NOT NULL,
  IS_CLUSTERED BOOLEAN NOT NULL,
  CONSTRAINT C_INDEXES_PK PRIMARY KEY (DB_ID, INDEX_NAME)
)