CREATE TABLE PARTITIONS (
  PID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  PARTITION_NAME VARCHAR(255),
  ORDINAL_POSITION INT NOT NULL,
  PARTITION_VALUE VARCHAR(1024),
  PATH VARCHAR(1024),
  CONSTRAINT C_PARTITION_PK PRIMARY KEY (PID),
  CONSTRAINT C_PARTITION_UNIQUE UNIQUE (TID, PARTITION_NAME)
)