CREATE TABLE PARTITION_METHODS (
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  PARTITION_TYPE VARCHAR(10) NOT NULL,
  EXPRESSION VARCHAR(1024) NOT NULL,
  EXPRESSION_SCHEMA VARCHAR(1024) FOR BIT DATA NOT NULL
)