CREATE TABLE OPTIONS (
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  KEY_ VARCHAR(255) NOT NULL,
  VALUE_ VARCHAR(255) NOT NULL,
  CONSTRAINT C_OPTIONS_UNIQUE UNIQUE (TID, KEY_, VALUE_)
)