CREATE TABLE TABLESPACES (
  SPACE_ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  SPACE_NAME VARCHAR(128) NOT NULL CONSTRAINT SPACE_UNIQUE UNIQUE,
  SPACE_HANDLER VARCHAR (1024) DEFAULT 'HDFS',
  SPACE_URI VARCHAR (4096) NOT NULL,
  CONSTRAINT C_SPACE_PK PRIMARY KEY (SPACE_ID)
)