CREATE TABLE PARTITIONS (
  PARTITION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TID INT NOT NULL,
  PARTITION_NAME VARCHAR(767) BINARY,
  PATH VARCHAR(4096),
  UNIQUE INDEX PARTITIONS_IDX (PARTITION_ID, TID, PARTITION_NAME),
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE)