CREATE TABLE PARTITION_KEYS (
  PID INT NOT NULL,
  COLUMN_NAME VARCHAR(255) BINARY NOT NULL,
  PARTITION_VALUE VARCHAR(255) NOT NULL,
  UNIQUE INDEX PARTITION_KEYS_IDX (PID, COLUMN_NAME, PARTITION_VALUE),
  FOREIGN KEY (PID) REFERENCES PARTITIONS (PID) ON DELETE CASCADE)