CREATE TABLE PARTITIONS (
  PID INT NOT NULL PRIMARY KEY,
  TID INT NOT NULL,
  PARTITION_NAME VARCHAR(128),
  ORDINAL_POSITION INT NOT NULL,
  PARTITION_VALUE VARCHAR(1024),
  PATH VARCHAR(4096),
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE,
  CONSTRAINT C_PARTITION_UNIQUE UNIQUE (TID, PARTITION_NAME),
  INDEX IDX_TID (TID),
  UNIQUE INDEX IDX_TID_NAME (TID, PARTITION_NAME)
)