CREATE TABLE PARTITION_METHODS (
  TID INT NOT NULL PRIMARY KEY,
  PARTITION_TYPE VARCHAR(10) NOT NULL,
  EXPRESSION VARCHAR(1024) NOT NULL,
  EXPRESSION_SCHEMA BYTEA NOT NULL,
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
)