CREATE TABLE PARTITION_KEYS (
  PID INT NOT NULL,
  IDX INT NOT NULL,
  PARTITION_VALUE VARCHAR(1024) NULL,
  CONSTRAINT PARTITION_KEYS_CONST UNIQUE (PID, IDX),
  FOREIGN KEY (PID) REFERENCES PARTITIONS (PID) ON DELETE CASCADE)