CREATE TABLE TABLES (
  TID SERIAL NOT NULL PRIMARY KEY,
  DB_ID INT NOT NULL,
  TABLE_NAME VARCHAR(128) NOT NULL,
  TABLE_TYPE VARCHAR(128) NOT NULL,
  PATH VARCHAR(4096),
  STORE_TYPE CHAR(16),
  FOREIGN KEY (DB_ID) REFERENCES DATABASES_ (DB_ID)
)