create external table if not exists ${DB}.web_sales
(
    ws_sold_date_sk           int4,
    ws_sold_time_sk           int4,
    ws_ship_date_sk           int4,
    ws_item_sk                int4,
    ws_bill_customer_sk       int4,
    ws_bill_cdemo_sk          int4,
    ws_bill_hdemo_sk          int4,
    ws_bill_addr_sk           int4,
    ws_ship_customer_sk       int4,
    ws_ship_cdemo_sk          int4,
    ws_ship_hdemo_sk          int4,
    ws_ship_addr_sk           int4,
    ws_web_page_sk            int4,
    ws_web_site_sk            int4,
    ws_ship_mode_sk           int4,
    ws_warehouse_sk           int4,
    ws_promo_sk               int4,
    ws_order_number           int4,
    ws_quantity               int4,
    ws_wholesale_cost         float4,
    ws_list_price             float4,
    ws_sales_price            float4,
    ws_ext_discount_amt       float4,
    ws_ext_sales_price        float4,
    ws_ext_wholesale_cost     float4,
    ws_ext_list_price         float4,
    ws_ext_tax                float4,
    ws_coupon_amt             float4,
    ws_ext_ship_cost          float4,
    ws_net_paid               float4,
    ws_net_paid_inc_tax       float4,
    ws_net_paid_inc_ship      float4,
    ws_net_paid_inc_ship_tax  float4,
    ws_net_profit             float4
)
using csv with ('text.delimiter'='|') location '${DATA_LOCATION}';