-- Against external table
CREATE TABLE IF NOT EXISTS default.LINEITEM (XXX TEXT);
CREATE TABLE IF NOT EXISTS default.LINEITEM AS SELECT 1;
CREATE TABLE IF NOT EXISTS default.LINEITEM AS SELECT * FROM default.LINEITEM;

-- Against managed table
CREATE TABLE T1 (NUM BIGINT);
CREATE TABLE IF NOT EXISTS T1 (XXX TEXT);
CREATE TABLE IF NOT EXISTS T1 AS SELECT 1;
CREATE TABLE IF NOT EXISTS T1 AS SELECT L_ORDERKEY FROM default.LINEITEM;
DROP TABLE T1;